//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegranteVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IntegranteVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.InsertarIntegranteWSResponse InsertarIntegranteWS(AppWindows.ServiceReference.InsertarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> InsertarIntegranteWSAsync(AppWindows.ServiceReference.InsertarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.ModificarIntegranteWSResponse ModificarIntegranteWS(AppWindows.ServiceReference.ModificarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> ModificarIntegranteWSAsync(AppWindows.ServiceReference.ModificarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.EliminarIntegranteWSResponse EliminarIntegranteWS(AppWindows.ServiceReference.EliminarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> EliminarIntegranteWSAsync(AppWindows.ServiceReference.EliminarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerIntegranteWSResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.ObtenerIntegranteWSResponse ObtenerIntegranteWS(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> ObtenerIntegranteWSAsync(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarIntegranteWSRequestBody Body;
        
        public InsertarIntegranteWSRequest() {
        }
        
        public InsertarIntegranteWSRequest(AppWindows.ServiceReference.InsertarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public InsertarIntegranteWSRequestBody() {
        }
        
        public InsertarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarIntegranteWSResponseBody Body;
        
        public InsertarIntegranteWSResponse() {
        }
        
        public InsertarIntegranteWSResponse(AppWindows.ServiceReference.InsertarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarIntegranteWSResponseBody {
        
        public InsertarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarIntegranteWSRequestBody Body;
        
        public ModificarIntegranteWSRequest() {
        }
        
        public ModificarIntegranteWSRequest(AppWindows.ServiceReference.ModificarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public ModificarIntegranteWSRequestBody() {
        }
        
        public ModificarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarIntegranteWSResponseBody Body;
        
        public ModificarIntegranteWSResponse() {
        }
        
        public ModificarIntegranteWSResponse(AppWindows.ServiceReference.ModificarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarIntegranteWSResponseBody {
        
        public ModificarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarIntegranteWSRequestBody Body;
        
        public EliminarIntegranteWSRequest() {
        }
        
        public EliminarIntegranteWSRequest(AppWindows.ServiceReference.EliminarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public EliminarIntegranteWSRequestBody() {
        }
        
        public EliminarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarIntegranteWSResponseBody Body;
        
        public EliminarIntegranteWSResponse() {
        }
        
        public EliminarIntegranteWSResponse(AppWindows.ServiceReference.EliminarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarIntegranteWSResponseBody {
        
        public EliminarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody Body;
        
        public ObtenerIntegranteWSRequest() {
        }
        
        public ObtenerIntegranteWSRequest(AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerIntegranteWSRequestBody() {
        }
        
        public ObtenerIntegranteWSRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerIntegranteWSResponseBody Body;
        
        public ObtenerIntegranteWSResponse() {
        }
        
        public ObtenerIntegranteWSResponse(AppWindows.ServiceReference.ObtenerIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIntegranteWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWSResult;
        
        public ObtenerIntegranteWSResponseBody() {
        }
        
        public ObtenerIntegranteWSResponseBody(AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWSResult) {
            this.ObtenerIntegranteWSResult = ObtenerIntegranteWSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : AppWindows.ServiceReference.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<AppWindows.ServiceReference.ServicioWebSoap>, AppWindows.ServiceReference.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.InsertarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.InsertarIntegranteWS(AppWindows.ServiceReference.InsertarIntegranteWSRequest request) {
            return base.Channel.InsertarIntegranteWS(request);
        }
        
        public void InsertarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.InsertarIntegranteWSRequest inValue = new AppWindows.ServiceReference.InsertarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.InsertarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.InsertarIntegranteWSAsync(AppWindows.ServiceReference.InsertarIntegranteWSRequest request) {
            return base.Channel.InsertarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> InsertarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.InsertarIntegranteWSRequest inValue = new AppWindows.ServiceReference.InsertarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ModificarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.ModificarIntegranteWS(AppWindows.ServiceReference.ModificarIntegranteWSRequest request) {
            return base.Channel.ModificarIntegranteWS(request);
        }
        
        public void ModificarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.ModificarIntegranteWSRequest inValue = new AppWindows.ServiceReference.ModificarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.ModificarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ModificarIntegranteWSAsync(AppWindows.ServiceReference.ModificarIntegranteWSRequest request) {
            return base.Channel.ModificarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> ModificarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.ModificarIntegranteWSRequest inValue = new AppWindows.ServiceReference.ModificarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.EliminarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.EliminarIntegranteWS(AppWindows.ServiceReference.EliminarIntegranteWSRequest request) {
            return base.Channel.EliminarIntegranteWS(request);
        }
        
        public void EliminarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.EliminarIntegranteWSRequest inValue = new AppWindows.ServiceReference.EliminarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.EliminarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.EliminarIntegranteWSAsync(AppWindows.ServiceReference.EliminarIntegranteWSRequest request) {
            return base.Channel.EliminarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> EliminarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.EliminarIntegranteWSRequest inValue = new AppWindows.ServiceReference.EliminarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ObtenerIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.ObtenerIntegranteWS(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request) {
            return base.Channel.ObtenerIntegranteWS(request);
        }
        
        public AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWS(int id) {
            AppWindows.ServiceReference.ObtenerIntegranteWSRequest inValue = new AppWindows.ServiceReference.ObtenerIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody();
            inValue.Body.id = id;
            AppWindows.ServiceReference.ObtenerIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerIntegranteWS(inValue);
            return retVal.Body.ObtenerIntegranteWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ObtenerIntegranteWSAsync(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request) {
            return base.Channel.ObtenerIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> ObtenerIntegranteWSAsync(int id) {
            AppWindows.ServiceReference.ObtenerIntegranteWSRequest inValue = new AppWindows.ServiceReference.ObtenerIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody();
            inValue.Body.id = id;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerIntegranteWSAsync(inValue);
        }
    }
}
