//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWindows.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegranteVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class IntegranteVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BandaVO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BandaVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroMusicalField;
        
        private int AnioCreacionField;
        
        private int AnioSeparacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWindows.ServiceReference.IntegranteVO[] IntegrantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GeneroMusical {
            get {
                return this.GeneroMusicalField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroMusicalField, value) != true)) {
                    this.GeneroMusicalField = value;
                    this.RaisePropertyChanged("GeneroMusical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AnioCreacion {
            get {
                return this.AnioCreacionField;
            }
            set {
                if ((this.AnioCreacionField.Equals(value) != true)) {
                    this.AnioCreacionField = value;
                    this.RaisePropertyChanged("AnioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AnioSeparacion {
            get {
                return this.AnioSeparacionField;
            }
            set {
                if ((this.AnioSeparacionField.Equals(value) != true)) {
                    this.AnioSeparacionField = value;
                    this.RaisePropertyChanged("AnioSeparacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AppWindows.ServiceReference.IntegranteVO[] Integrantes {
            get {
                return this.IntegrantesField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegrantesField, value) != true)) {
                    this.IntegrantesField = value;
                    this.RaisePropertyChanged("Integrantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.InsertarIntegranteWSResponse InsertarIntegranteWS(AppWindows.ServiceReference.InsertarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> InsertarIntegranteWSAsync(AppWindows.ServiceReference.InsertarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.ModificarIntegranteWSResponse ModificarIntegranteWS(AppWindows.ServiceReference.ModificarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> ModificarIntegranteWSAsync(AppWindows.ServiceReference.ModificarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento integranteVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.EliminarIntegranteWSResponse EliminarIntegranteWS(AppWindows.ServiceReference.EliminarIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> EliminarIntegranteWSAsync(AppWindows.ServiceReference.EliminarIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerIntegranteWSResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIntegranteWS", ReplyAction="*")]
        AppWindows.ServiceReference.ObtenerIntegranteWSResponse ObtenerIntegranteWS(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIntegranteWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> ObtenerIntegranteWSAsync(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bandaVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarBandaWS", ReplyAction="*")]
        AppWindows.ServiceReference.InsertarBandaWSResponse InsertarBandaWS(AppWindows.ServiceReference.InsertarBandaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarBandaWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarBandaWSResponse> InsertarBandaWSAsync(AppWindows.ServiceReference.InsertarBandaWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bandaVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarBandaWS", ReplyAction="*")]
        AppWindows.ServiceReference.ModificarBandaWSResponse ModificarBandaWS(AppWindows.ServiceReference.ModificarBandaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarBandaWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarBandaWSResponse> ModificarBandaWSAsync(AppWindows.ServiceReference.ModificarBandaWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bandaVO del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarBandaWS", ReplyAction="*")]
        AppWindows.ServiceReference.EliminarBandaWSResponse EliminarBandaWS(AppWindows.ServiceReference.EliminarBandaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarBandaWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarBandaWSResponse> EliminarBandaWSAsync(AppWindows.ServiceReference.EliminarBandaWSRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerBandaWSResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBandaWS", ReplyAction="*")]
        AppWindows.ServiceReference.ObtenerBandaWSResponse ObtenerBandaWS(AppWindows.ServiceReference.ObtenerBandaWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBandaWS", ReplyAction="*")]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerBandaWSResponse> ObtenerBandaWSAsync(AppWindows.ServiceReference.ObtenerBandaWSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarIntegranteWSRequestBody Body;
        
        public InsertarIntegranteWSRequest() {
        }
        
        public InsertarIntegranteWSRequest(AppWindows.ServiceReference.InsertarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public InsertarIntegranteWSRequestBody() {
        }
        
        public InsertarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarIntegranteWSResponseBody Body;
        
        public InsertarIntegranteWSResponse() {
        }
        
        public InsertarIntegranteWSResponse(AppWindows.ServiceReference.InsertarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarIntegranteWSResponseBody {
        
        public InsertarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarIntegranteWSRequestBody Body;
        
        public ModificarIntegranteWSRequest() {
        }
        
        public ModificarIntegranteWSRequest(AppWindows.ServiceReference.ModificarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public ModificarIntegranteWSRequestBody() {
        }
        
        public ModificarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarIntegranteWSResponseBody Body;
        
        public ModificarIntegranteWSResponse() {
        }
        
        public ModificarIntegranteWSResponse(AppWindows.ServiceReference.ModificarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarIntegranteWSResponseBody {
        
        public ModificarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarIntegranteWSRequestBody Body;
        
        public EliminarIntegranteWSRequest() {
        }
        
        public EliminarIntegranteWSRequest(AppWindows.ServiceReference.EliminarIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO integranteVO;
        
        public EliminarIntegranteWSRequestBody() {
        }
        
        public EliminarIntegranteWSRequestBody(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            this.integranteVO = integranteVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarIntegranteWSResponseBody Body;
        
        public EliminarIntegranteWSResponse() {
        }
        
        public EliminarIntegranteWSResponse(AppWindows.ServiceReference.EliminarIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarIntegranteWSResponseBody {
        
        public EliminarIntegranteWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegranteWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegranteWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody Body;
        
        public ObtenerIntegranteWSRequest() {
        }
        
        public ObtenerIntegranteWSRequest(AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIntegranteWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerIntegranteWSRequestBody() {
        }
        
        public ObtenerIntegranteWSRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIntegranteWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIntegranteWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerIntegranteWSResponseBody Body;
        
        public ObtenerIntegranteWSResponse() {
        }
        
        public ObtenerIntegranteWSResponse(AppWindows.ServiceReference.ObtenerIntegranteWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIntegranteWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWSResult;
        
        public ObtenerIntegranteWSResponseBody() {
        }
        
        public ObtenerIntegranteWSResponseBody(AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWSResult) {
            this.ObtenerIntegranteWSResult = ObtenerIntegranteWSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarBandaWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarBandaWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarBandaWSRequestBody Body;
        
        public InsertarBandaWSRequest() {
        }
        
        public InsertarBandaWSRequest(AppWindows.ServiceReference.InsertarBandaWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarBandaWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.BandaVO bandaVO;
        
        public InsertarBandaWSRequestBody() {
        }
        
        public InsertarBandaWSRequestBody(AppWindows.ServiceReference.BandaVO bandaVO) {
            this.bandaVO = bandaVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarBandaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarBandaWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.InsertarBandaWSResponseBody Body;
        
        public InsertarBandaWSResponse() {
        }
        
        public InsertarBandaWSResponse(AppWindows.ServiceReference.InsertarBandaWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarBandaWSResponseBody {
        
        public InsertarBandaWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarBandaWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarBandaWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarBandaWSRequestBody Body;
        
        public ModificarBandaWSRequest() {
        }
        
        public ModificarBandaWSRequest(AppWindows.ServiceReference.ModificarBandaWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarBandaWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.BandaVO bandaVO;
        
        public ModificarBandaWSRequestBody() {
        }
        
        public ModificarBandaWSRequestBody(AppWindows.ServiceReference.BandaVO bandaVO) {
            this.bandaVO = bandaVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarBandaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarBandaWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ModificarBandaWSResponseBody Body;
        
        public ModificarBandaWSResponse() {
        }
        
        public ModificarBandaWSResponse(AppWindows.ServiceReference.ModificarBandaWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarBandaWSResponseBody {
        
        public ModificarBandaWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarBandaWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarBandaWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarBandaWSRequestBody Body;
        
        public EliminarBandaWSRequest() {
        }
        
        public EliminarBandaWSRequest(AppWindows.ServiceReference.EliminarBandaWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarBandaWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.BandaVO bandaVO;
        
        public EliminarBandaWSRequestBody() {
        }
        
        public EliminarBandaWSRequestBody(AppWindows.ServiceReference.BandaVO bandaVO) {
            this.bandaVO = bandaVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarBandaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarBandaWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.EliminarBandaWSResponseBody Body;
        
        public EliminarBandaWSResponse() {
        }
        
        public EliminarBandaWSResponse(AppWindows.ServiceReference.EliminarBandaWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarBandaWSResponseBody {
        
        public EliminarBandaWSResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerBandaWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerBandaWS", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerBandaWSRequestBody Body;
        
        public ObtenerBandaWSRequest() {
        }
        
        public ObtenerBandaWSRequest(AppWindows.ServiceReference.ObtenerBandaWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerBandaWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerBandaWSRequestBody() {
        }
        
        public ObtenerBandaWSRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerBandaWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerBandaWSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppWindows.ServiceReference.ObtenerBandaWSResponseBody Body;
        
        public ObtenerBandaWSResponse() {
        }
        
        public ObtenerBandaWSResponse(AppWindows.ServiceReference.ObtenerBandaWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerBandaWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppWindows.ServiceReference.BandaVO ObtenerBandaWSResult;
        
        public ObtenerBandaWSResponseBody() {
        }
        
        public ObtenerBandaWSResponseBody(AppWindows.ServiceReference.BandaVO ObtenerBandaWSResult) {
            this.ObtenerBandaWSResult = ObtenerBandaWSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : AppWindows.ServiceReference.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<AppWindows.ServiceReference.ServicioWebSoap>, AppWindows.ServiceReference.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.InsertarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.InsertarIntegranteWS(AppWindows.ServiceReference.InsertarIntegranteWSRequest request) {
            return base.Channel.InsertarIntegranteWS(request);
        }
        
        public void InsertarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.InsertarIntegranteWSRequest inValue = new AppWindows.ServiceReference.InsertarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.InsertarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.InsertarIntegranteWSAsync(AppWindows.ServiceReference.InsertarIntegranteWSRequest request) {
            return base.Channel.InsertarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarIntegranteWSResponse> InsertarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.InsertarIntegranteWSRequest inValue = new AppWindows.ServiceReference.InsertarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ModificarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.ModificarIntegranteWS(AppWindows.ServiceReference.ModificarIntegranteWSRequest request) {
            return base.Channel.ModificarIntegranteWS(request);
        }
        
        public void ModificarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.ModificarIntegranteWSRequest inValue = new AppWindows.ServiceReference.ModificarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.ModificarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ModificarIntegranteWSAsync(AppWindows.ServiceReference.ModificarIntegranteWSRequest request) {
            return base.Channel.ModificarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarIntegranteWSResponse> ModificarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.ModificarIntegranteWSRequest inValue = new AppWindows.ServiceReference.ModificarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.EliminarIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.EliminarIntegranteWS(AppWindows.ServiceReference.EliminarIntegranteWSRequest request) {
            return base.Channel.EliminarIntegranteWS(request);
        }
        
        public void EliminarIntegranteWS(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.EliminarIntegranteWSRequest inValue = new AppWindows.ServiceReference.EliminarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            AppWindows.ServiceReference.EliminarIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarIntegranteWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.EliminarIntegranteWSAsync(AppWindows.ServiceReference.EliminarIntegranteWSRequest request) {
            return base.Channel.EliminarIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarIntegranteWSResponse> EliminarIntegranteWSAsync(AppWindows.ServiceReference.IntegranteVO integranteVO) {
            AppWindows.ServiceReference.EliminarIntegranteWSRequest inValue = new AppWindows.ServiceReference.EliminarIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarIntegranteWSRequestBody();
            inValue.Body.integranteVO = integranteVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ObtenerIntegranteWSResponse AppWindows.ServiceReference.ServicioWebSoap.ObtenerIntegranteWS(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request) {
            return base.Channel.ObtenerIntegranteWS(request);
        }
        
        public AppWindows.ServiceReference.IntegranteVO ObtenerIntegranteWS(int id) {
            AppWindows.ServiceReference.ObtenerIntegranteWSRequest inValue = new AppWindows.ServiceReference.ObtenerIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody();
            inValue.Body.id = id;
            AppWindows.ServiceReference.ObtenerIntegranteWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerIntegranteWS(inValue);
            return retVal.Body.ObtenerIntegranteWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ObtenerIntegranteWSAsync(AppWindows.ServiceReference.ObtenerIntegranteWSRequest request) {
            return base.Channel.ObtenerIntegranteWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerIntegranteWSResponse> ObtenerIntegranteWSAsync(int id) {
            AppWindows.ServiceReference.ObtenerIntegranteWSRequest inValue = new AppWindows.ServiceReference.ObtenerIntegranteWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerIntegranteWSRequestBody();
            inValue.Body.id = id;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerIntegranteWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.InsertarBandaWSResponse AppWindows.ServiceReference.ServicioWebSoap.InsertarBandaWS(AppWindows.ServiceReference.InsertarBandaWSRequest request) {
            return base.Channel.InsertarBandaWS(request);
        }
        
        public void InsertarBandaWS(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.InsertarBandaWSRequest inValue = new AppWindows.ServiceReference.InsertarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            AppWindows.ServiceReference.InsertarBandaWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarBandaWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarBandaWSResponse> AppWindows.ServiceReference.ServicioWebSoap.InsertarBandaWSAsync(AppWindows.ServiceReference.InsertarBandaWSRequest request) {
            return base.Channel.InsertarBandaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.InsertarBandaWSResponse> InsertarBandaWSAsync(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.InsertarBandaWSRequest inValue = new AppWindows.ServiceReference.InsertarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.InsertarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).InsertarBandaWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ModificarBandaWSResponse AppWindows.ServiceReference.ServicioWebSoap.ModificarBandaWS(AppWindows.ServiceReference.ModificarBandaWSRequest request) {
            return base.Channel.ModificarBandaWS(request);
        }
        
        public void ModificarBandaWS(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.ModificarBandaWSRequest inValue = new AppWindows.ServiceReference.ModificarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            AppWindows.ServiceReference.ModificarBandaWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarBandaWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarBandaWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ModificarBandaWSAsync(AppWindows.ServiceReference.ModificarBandaWSRequest request) {
            return base.Channel.ModificarBandaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ModificarBandaWSResponse> ModificarBandaWSAsync(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.ModificarBandaWSRequest inValue = new AppWindows.ServiceReference.ModificarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ModificarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ModificarBandaWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.EliminarBandaWSResponse AppWindows.ServiceReference.ServicioWebSoap.EliminarBandaWS(AppWindows.ServiceReference.EliminarBandaWSRequest request) {
            return base.Channel.EliminarBandaWS(request);
        }
        
        public void EliminarBandaWS(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.EliminarBandaWSRequest inValue = new AppWindows.ServiceReference.EliminarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            AppWindows.ServiceReference.EliminarBandaWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarBandaWS(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarBandaWSResponse> AppWindows.ServiceReference.ServicioWebSoap.EliminarBandaWSAsync(AppWindows.ServiceReference.EliminarBandaWSRequest request) {
            return base.Channel.EliminarBandaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.EliminarBandaWSResponse> EliminarBandaWSAsync(AppWindows.ServiceReference.BandaVO bandaVO) {
            AppWindows.ServiceReference.EliminarBandaWSRequest inValue = new AppWindows.ServiceReference.EliminarBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.EliminarBandaWSRequestBody();
            inValue.Body.bandaVO = bandaVO;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).EliminarBandaWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWindows.ServiceReference.ObtenerBandaWSResponse AppWindows.ServiceReference.ServicioWebSoap.ObtenerBandaWS(AppWindows.ServiceReference.ObtenerBandaWSRequest request) {
            return base.Channel.ObtenerBandaWS(request);
        }
        
        public AppWindows.ServiceReference.BandaVO ObtenerBandaWS(int id) {
            AppWindows.ServiceReference.ObtenerBandaWSRequest inValue = new AppWindows.ServiceReference.ObtenerBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerBandaWSRequestBody();
            inValue.Body.id = id;
            AppWindows.ServiceReference.ObtenerBandaWSResponse retVal = ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerBandaWS(inValue);
            return retVal.Body.ObtenerBandaWSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerBandaWSResponse> AppWindows.ServiceReference.ServicioWebSoap.ObtenerBandaWSAsync(AppWindows.ServiceReference.ObtenerBandaWSRequest request) {
            return base.Channel.ObtenerBandaWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWindows.ServiceReference.ObtenerBandaWSResponse> ObtenerBandaWSAsync(int id) {
            AppWindows.ServiceReference.ObtenerBandaWSRequest inValue = new AppWindows.ServiceReference.ObtenerBandaWSRequest();
            inValue.Body = new AppWindows.ServiceReference.ObtenerBandaWSRequestBody();
            inValue.Body.id = id;
            return ((AppWindows.ServiceReference.ServicioWebSoap)(this)).ObtenerBandaWSAsync(inValue);
        }
    }
}
